apiVersion: v1
kind: Service
metadata:
    name: service-validator-front
spec:
    type: ClusterIP
    ports:
        - name: http
          port: 80
          targetPort: 80
          protocol: TCP
    selector:
        app: deployment-validator-front
