apiVersion: v1
kind: Service
metadata:
  name: service-validator-back
spec:
  type: ClusterIP
  ports:
    - name: port-80
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: validator-back

